### ISSUE TITLE
Backlog Item. Can't add a checkbox custom field

### ISSUE THREAD

**Issue by AKlaus** [ravendb/samples-yabt#23]
## Steps to reproduce
1. Open an backlog item
2. Add a custom field with type 'checkbox' and with ticked or not value
![image](https://user-images.githubusercontent.com/4317919/119812414-79080600-bf2b-11eb-81d9-1fa9c10cd35f.png)
3. Save the backlog item and you get an error: `Specified argument was out of the range of valid values. (Parameter 'Unsupported field type: Checkbox')`

### Call stack:
```
at Raven.Yabt.Domain.BacklogItemServices.Commands.BacklogItemDtoToEntityConversion.ResolveChangedCustomFields(IDictionary`2 existingFields, IList`1 actions) in /Users/alex/Documents/Job/Raven/YABT/back-end/Domain/BacklogItemServices/Commands/BacklogItemDtoToEntityConversion.cs:line 175
at Raven.Yabt.Domain.BacklogItemServices.Commands.BacklogItemDtoToEntityConversion.ConvertToEntity[TModel,TDto](TDto dto, TModel entity) in /Users/alex/Documents/Job/Raven/YABT/back-end/Domain/BacklogItemServices/Commands/BacklogItemDtoToEntityConversion.cs:line 65 
at Raven.Yabt.Domain.BacklogItemServices.Commands.BacklogItemCommandService.Update[T](String id, T dto) in /Users/alex/Documents/Job/Raven/YABT/back-end/Domain/BacklogItemServices/Commands/BacklogItemCommandService.cs:line 58 
at DomainResults.Mvc.DomainResultExtensions.ToActionResultOfT[T](Task`1 domainResultTask, Action`2 errorAction)
...
```

**Comment by AKlaus** [comment]
fixed
